---
global:
  scrape_interval: 15s
  scrape_timeout: 15s
rule_files:
  - "alert.rules"
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 127.0.0.1:9090

- job_name: node
  static_configs:
  - targets:
    - 192.168.0.22:9100
    - 192.168.0.82:9100
    - 192.168.0.85:9100
    - 192.168.0.87:9100
    - 192.168.0.43:9100
    - 192.168.0.93:9100
    - 192.168.0.74:9100

- job_name: 'jira'
  scheme: http #change to http if don't you have https
  metrics_path: '/jira/plugins/servlet/prometheus/metrics'
  params:
       token: ['nAqL7MgXONEuf0lcZ2kQ9pghFxp42bUZM1N'] # i'd reccomend use 128 symbol lenght long [A-Za-z0-9]
  static_configs:
    - targets: ['192.168.0.85:8090']
#- job_name: "apache"
#  static_configs:
#    - targets: ['192.168.0.22:9117']

- job_name: 'gitlab-process'
  metrics_path: /process
  static_configs:
    - targets: ['localhost:9168']

- job_name: 'gitlab-sidekiq'
  metrics_path: /sidekiq
  static_configs:
    - targets: ['localhost:9168']

- job_name: 'confluence'
  scheme: https #change to http if don't you have https
  metrics_path: '/confluence/plugins/servlet/prometheus/metrics'
  params:
       token: ['mFoSHgespZhuXA1UozLswhDUhyKDilM0oww'] # i'd reccomend use 128 symbol lenght long [A-Za-z0-9]
  static_configs:
    - targets: ['192.168.0.82:7440']

- job_name: blackbox_site_monitoring
  scrape_interval: 5s
  metrics_path: /probe
  params:
    module: [http_200_module]
  static_configs:
    - targets:
      - https://tools.com/jira
      - https://confluence.com
      - https://tools-nad.com/prometheus
      - https://gitlab.com
      - https://tools.com/qa-jira
      - https://tools.com/sonar
      - https://jenkins.com
      
      labels:
          group: 'prod_site'
  relabel_configs:
    - source_labels: [__address__]
      regex: (.*)(:80)?
      target_label: __param_target
      replacement: ${1}
    - source_labels: [__param_target]
      regex: (.*)
      target_label: instance
      replacement: ${1}
    - source_labels: []
      regex: .*
      target_label: __address__
      replacement: 127.0.0.1:9115    # Blackbox exporter URL.
